@domain = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDM0MjkwNTd9.iuCRkp1NpzCw67vdWZbPVd6KOKXV_3f9fD40XJn-nG0

### Produts Index
GET {{ domain }}/products?category=cheap

### Produts Create
POST {{ domain }}/products
Content-Type: application/json
Authorization: Bearer {{ jwt }}


{
  "name": "Liver",
  "price": "50",
  "description": "A large lobed glandular organ in the abdomen of vertebrates, involved in many metabolic processes.",
  "quantity": 10,
  "supplier_id": 1
}

### Products Show
GET {{ domain }}/products/2

### Products Update
PATCH {{ domain }}/products/1
Content-Type: application/json

{
  "quantity": 6
}

### Products Destroy
DELETE {{ domain }}/products/1

### Users create (signup)
POST {{ domain }}/users
Content-Type: application/json

{
  "name": "Chris Jones",
  "email": "cdineroj@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Orders index
GET {{ domain }}/orders
Authorization: Bearer {{ jwt }}

### Orders create
POST {{ domain }}/orders
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "product_id": 4,
  "quantity": 5
}

### Orders show
GET {{ domain }}/orders/3
Authorization: Bearer {{ jwt }}