
   
@domain = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDM0OTE4NjV9.04EbfTXoRtdjJYf3tmPjH-8KyDlyAHkP5lNGQd99Bn8

### Produts Index
GET {{ domain }}/products?category=Organ

### Produts Create
POST {{ domain }}/products
Content-Type: application/json
Authorization: Bearer {{ jwt }}


{
  "name": "Toe",
  "price": "50",
  "description": "A finger on your foot",
  "quantity": 6,
  "supplier_id": 2
}

### Products Show
GET {{ domain }}/products/2

### Products Update
PATCH {{ domain }}/products/1
Content-Type: application/json

{
  "quantity": 6
}

### Products Destroy
DELETE {{ domain }}/products/1

### Users create (signup)
POST {{ domain }}/users
Content-Type: application/json

{
  "name": "Davie",
  "email": "Dave@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Orders index
GET {{ domain }}/orders
Authorization: Bearer {{ jwt }}

### Orders create
POST {{ domain }}/orders
Authorization: Bearer {{ jwt }}

### Orders show
GET {{ domain }}/orders/3
Authorization: Bearer {{ jwt }}

### Carted Products Index
GET {{ domain }}/carted_products
Authorization: Bearer {{ jwt }}

### Carted Products Create
POST {{ domain }}/carted_products
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "product_id": 1,
  "quantity": 2
}